### ISSUE TITLE
Use Travis pages provider

### ISSUE THREAD

**Issue by ghost** [cpp-tour/cpp-tour#42]
As mentioned in the cpp-tour chat, `deploy.sh` is basically doing what the [pages provider](https://docs.travis-ci.com/user/deployment/pages/) already does. Switching over is trivial, you just need something like this in your `.travis.yml`:

```
deploy:
    provider: pages
    skip_cleanup: true
    github_token: ${GIT_TOKEN}
    fqdn: cpp-tour.com
    local_dir: public
    keep_history: true
    name: Travis CI
    email: github@arvid.io
    on:
        branch: master
```

Note that the `keep_history` flag is in a [PR that hasn't been merged yet](https://github.com/travis-ci/dpl/pull/719).

Since you are using Cloudflare, I also recommend adding this so that the cache is cleared upon a build:

```
after_deploy:
  - |
    curl -X DELETE "https://api.cloudflare.com/client/v4/zones/${CF_ZONE_ID}/purge_cache" \
     -H "X-Auth-Email: ${CF_EMAIL}" \
     -H "X-Auth-Key: ${CF_API_KEY}" \
     -H "Content-Type: application/json" \
     --data '{"purge_everything":true}'
```

That can be adjusted as needed to your preferences.
